"""Minimal Nemo extension core for status lookups.

The real nemo-python entry point is generated by the installer so development
installs can point Nemo at this source tree without requiring pip install -e.
"""

from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
import json
import os
from pathlib import Path
import subprocess
import time
from typing import Sequence

from . import status_client


DEFAULT_MAX_VISIBLE_ITEMS = 2048

PRIMARY_EMBLEMS = {
    "conflicted": "nemovcs-conflicted",
    "modified": "nemovcs-modified",
    "ok": "nemovcs-normal",
}
MENU_ICON = "nemovcs"


@dataclass(frozen=True)
class MenuActionSpec:
    name: str
    label: str
    command: tuple[str, ...] = ()
    tip: str = ""
    icon: str = MENU_ICON
    separator: bool = False


class NemoVCSInfoProviderCore:
    def __init__(
        self,
        *,
        cache: status_client.StatusClientCache | None = None,
        seen=None,
        get_status=None,
        diagnostics=None,
        max_visible_items: int = DEFAULT_MAX_VISIBLE_ITEMS,
    ):
        if max_visible_items < 1:
            raise ValueError("max_visible_items must be at least 1")
        self.cache = cache if cache is not None else status_client.StatusClientCache()
        self.seen = seen
        self.get_status = get_status
        self.diagnostics = (
            diagnostics
            if diagnostics is not None
            else PluginDiagnostics.from_environment()
        )
        self.max_visible_items = max_visible_items
        self.visible_items: OrderedDict[str, object] = OrderedDict()
        self.last_error = ""

    def item_path(self, item) -> str | None:
        try:
            if item.get_uri_scheme() != "file":
                self.log("ignore-item", reason="non-file-uri")
                return None
            location = item.get_location()
            path = location.get_path()
        except Exception as exc:
            self.last_error = str(exc)
            self.log("item-error", error=self.last_error)
            return None

        return str(Path(path).resolve(strict=False)) if path else None

    def update_item(self, item) -> dict[str, str] | None:
        path = self.item_path(item)
        if path is None:
            return None
        self.track_visible_item(path, item)
        record = self.update_path(path)
        emblem = self.apply_emblem(item, record)
        self.log(
            "update-item",
            path=path,
            status=record.get("status", "") if record else "",
            emblem=emblem or "",
        )
        return record

    def update_path(self, path: str | Path) -> dict[str, str] | None:
        seen = self.seen or default_seen
        get_status = self.get_status or default_get_status
        for attempt in range(1, 3):
            try:
                records = self.cache.refresh([path], seen, get_status)
                break
            except Exception as exc:
                self.last_error = str(exc)
                self.log(
                    "status-error",
                    path=str(path),
                    attempt=attempt,
                    error=self.last_error,
                )
                if attempt == 2:
                    return None

        self.last_error = ""
        record = records[0] if records else None
        self.log(
            "status",
            path=str(path),
            status=record.get("status", "") if record else "",
            worktree_id=record.get("worktree_id", "") if record else "",
        )
        return record

    def apply_emblem(self, item, record: dict[str, str] | None) -> str | None:
        if not record:
            return None

        emblem = primary_emblem(record.get("status", ""))
        if emblem is None:
            return None

        try:
            item.add_emblem(emblem)
        except Exception as exc:
            self.last_error = str(exc)
            self.log("emblem-error", emblem=emblem, error=self.last_error)
            return None

        return emblem

    def track_visible_item(self, path: str | Path, item) -> None:
        key = status_client.normalize_path(path)
        if key in self.visible_items:
            del self.visible_items[key]
        self.visible_items[key] = item
        self.visible_items.move_to_end(key, last=False)
        while len(self.visible_items) > self.max_visible_items:
            self.visible_items.popitem(last=True)

    def on_status_changed(
        self,
        worktree_id: str,
        changed_paths,
    ) -> list[str]:
        affected_paths = self.affected_visible_paths(worktree_id, changed_paths)
        removed = self.cache.invalidate(worktree_id, changed_paths)
        invalidated = [
            path
            for path in affected_paths
            if self.invalidate_visible_item(path)
        ]
        self.log(
            "status-changed",
            worktree_id=str(worktree_id),
            changed_count=len(changed_paths),
            affected_count=len(affected_paths),
            removed_count=len(removed),
            invalidated_count=len(invalidated),
        )
        return invalidated

    def affected_visible_paths(self, worktree_id: str, changed_paths) -> list[str]:
        changed = [status_client.normalize_path(path) for path in changed_paths]
        affected: list[str] = []
        for path in self.visible_items:
            record = self.cache.get(path)
            if record is None or record.get("worktree_id") != str(worktree_id):
                continue
            if not changed or any(
                status_client.paths_overlap(path, changed_path)
                for changed_path in changed
            ):
                affected.append(path)
        return affected

    def invalidate_visible_item(self, path: str | Path) -> bool:
        item = self.visible_items.get(status_client.normalize_path(path))
        if item is None:
            return False

        invalidate = getattr(item, "invalidate_extension_info", None)
        if invalidate is None:
            return False

        try:
            invalidate()
        except Exception as exc:
            self.last_error = str(exc)
            self.log("invalidate-error", path=str(path), error=self.last_error)
            return False
        return True

    def log(self, event: str, **fields) -> None:
        if self.diagnostics is not None:
            self.diagnostics.log(event, **fields)

    def menu_paths(self, items) -> list[str]:
        paths: list[str] = []
        for item in items:
            path = self.item_path(item)
            if path is not None:
                paths.append(path)
        return paths

    def submenu_specs(self, paths: Sequence[str | Path]) -> list[MenuActionSpec]:
        normalized = [str(Path(path).resolve(strict=False)) for path in paths]
        if not normalized:
            return []

        if all(is_clone_target(path) for path in normalized):
            return clone_menu_specs(normalized)

        backend_id = selected_backend_id(normalized)
        if backend_id == "git":
            return git_menu_specs(normalized)
        if backend_id == "svn":
            return svn_menu_specs(normalized)
        return []


class PluginDiagnostics:
    def __init__(self, path: str | Path):
        self.path = Path(path).expanduser()

    @classmethod
    def from_environment(cls):
        path = os.environ.get("NEMOVCS_PLUGIN_LOG")
        return cls(path) if path else None

    def log(self, event: str, **fields) -> None:
        record = {"time": time.time(), "event": event, **fields}
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps(record, sort_keys=True) + "\n")
        except OSError:
            pass


class NemoVCSInfoProviderMixin:
    def __init__(self):
        self.nemovcs_core = NemoVCSInfoProviderCore()
        self.nemovcs_signal_subscription = None
        self.subscribe_status_changed()
        self.nemovcs_core.log("provider-init")

    def update_file_info(self, item):
        from gi.repository import Nemo

        self.nemovcs_core.update_item(item)
        return Nemo.OperationResult.COMPLETE

    def get_file_items(self, _window, items):
        paths = self.nemovcs_core.menu_paths(items)
        return self.nemovcs_menu_items(paths)

    def get_background_items(self, _window, item):
        path = self.nemovcs_core.item_path(item)
        return self.nemovcs_menu_items([path] if path else [])

    def nemovcs_menu_items(self, paths: Sequence[str]) -> list[object]:
        specs = self.nemovcs_core.submenu_specs(paths)
        if not specs:
            return []

        from gi.repository import Nemo

        submenu_item = Nemo.MenuItem(
            name="NemoVCS::Menu",
            label="NemoVCS",
            tip="NemoVCS actions",
            icon=MENU_ICON,
        )
        submenu = Nemo.Menu()
        submenu_item.set_submenu(submenu)

        for spec in specs:
            if spec.separator:
                submenu.append_item(Nemo.MenuItem.new_separator(spec.name))
                continue
            item = Nemo.MenuItem(
                name=spec.name,
                label=spec.label,
                tip=spec.tip,
                icon=spec.icon,
            )
            item.connect("activate", self.on_menu_item_activate, spec.command)
            submenu.append_item(item)

        return [submenu_item]

    def on_menu_item_activate(self, _item, command: Sequence[str]) -> None:
        try:
            subprocess.Popen(list(command))
        except OSError as exc:
            self.nemovcs_core.last_error = str(exc)
            self.nemovcs_core.log(
                "menu-spawn-error",
                command=" ".join(command),
                error=str(exc),
            )

    def subscribe_status_changed(self) -> bool:
        try:
            self.nemovcs_signal_subscription = subscribe_daemon_status_changed(
                self.nemovcs_core.on_status_changed
            )
        except Exception as exc:
            self.nemovcs_core.last_error = str(exc)
            return False
        return True


def default_seen(paths):
    from . import statusd_dbus

    return statusd_dbus.call_seen(paths)


def default_get_status(paths):
    from . import statusd_dbus

    return statusd_dbus.call_get_status(paths)


def subscribe_daemon_status_changed(callback):
    import dbus.mainloop.glib

    from . import statusd_dbus

    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    return statusd_dbus.subscribe_status_changed(callback)


def primary_emblem(status: str) -> str | None:
    return PRIMARY_EMBLEMS.get(status)


def selected_backend_id(paths: Sequence[str | Path]) -> str | None:
    from . import backends

    for backend in backends.registered_backends():
        if all(backend.is_worktree(path) for path in paths):
            return backend.id
    return None


def is_clone_target(path: str | Path) -> bool:
    from . import backends

    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    candidate = candidate.resolve(strict=False)
    return candidate.is_dir() and backends.detect_backend(candidate) is None


def git_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    return [
        action("GitStage", "Stage...", ["stage-dialog", "--operation", "stage", *paths]),
        action("GitRevert", "Revert...", ["revert-dialog", *paths]),
        action("GitPush", "Push...", ["push-dialog", *paths]),
        separator("GitSep1"),
        action("GitStatus", "Status...", ["status-dialog", *paths]),
        action("GitLog", "Log...", ["log-dialog", *paths]),
        separator("GitSep2"),
        action("GitSettings", "Settings...", ["settings-dialog"]),
        action("GitAbout", "About...", ["about-dialog"]),
    ]


def svn_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    return [
        action("SvnAdd", "Add...", ["stage-dialog", "--operation", "add", *paths]),
        action("SvnRevert", "Revert...", ["revert-dialog", *paths]),
        separator("SvnSep1"),
        action("SvnStatus", "Status...", ["status-dialog", *paths]),
        action("SvnLog", "Log...", ["log-dialog", *paths]),
        separator("SvnSep2"),
        action("SvnSettings", "Settings...", ["settings-dialog"]),
        action("SvnAbout", "About...", ["about-dialog"]),
    ]


def clone_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    return [
        action("GitClone", "Git Clone...", ["clone-dialog", "--vcs", "git", *paths]),
        action("SvnCheckout", "SVN Checkout...", ["clone-dialog", "--vcs", "svn", *paths]),
        separator("CloneSep1"),
        action("CloneSettings", "Settings...", ["settings-dialog"]),
        action("CloneAbout", "About...", ["about-dialog"]),
    ]


def action(name: str, label: str, args: Sequence[str]) -> MenuActionSpec:
    return MenuActionSpec(
        name=f"NemoVCS::{name}",
        label=label,
        command=("nemovcs", *args),
        tip=label.removesuffix("..."),
    )


def separator(name: str) -> MenuActionSpec:
    return MenuActionSpec(name=f"NemoVCS::{name}", label="", separator=True)
