"""Minimal Nemo extension core for status lookups.

The real nemo-python entry point is generated by the installer so development
installs can point Nemo at this source tree without requiring pip install -e.
"""

from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
from html import escape
import json
import os
from pathlib import Path
import subprocess
import sys
import time
from typing import Sequence
from urllib.parse import unquote, urlparse

from . import status_client


DEFAULT_MAX_VISIBLE_ITEMS = 2048
LOCATION_BAR_MAX_CHARS = 32
LOCATION_WIDGET_REFRESH_RETRY_MS = 250
LOCATION_WIDGET_MAX_REFRESH_RETRIES = 12

PRIMARY_EMBLEMS = {
    "conflicted": "nemovcs-conflicted",
    "error": "nemovcs-problems",
    "modified": "nemovcs-modified",
    "unversioned": "nemovcs-unversioned",
    "ok": "nemovcs-normal",
}
DIFFABLE_STATUSES = {"conflicted", "modified"}
MENU_ICON = "nemovcs"
ABOUT_ICON = MENU_ICON
ADD_ICON = "nemovcs-add"
CHECKOUT_ICON = "nemovcs-checkout"
COMMIT_ICON = "nemovcs-commit"
DIFF_ICON = "nemovcs-diff"
GIT_ICON = "nemovcs-git"
LOG_ICON = "nemovcs-show-log"
MODIFIED_MENU_ICON = "emblem-nemovcs-modified"
PUSH_ICON = "nemovcs-push"
RENAME_ICON = "nemovcs-rename"
REVERT_ICON = "nemovcs-revert"
SETTINGS_ICON = "nemovcs-settings"
STATUS_ICON = "nemovcs-status"
SVN_ICON = "nemovcs-svn"
UPDATE_ICON = "nemovcs-update"
BACKEND_LABELS = {
    "git": "Git",
    "svn": "SVN",
}
BACKEND_ICONS = {
    "git": GIT_ICON,
    "svn": SVN_ICON,
}
STATUS_LABELS = {
    "conflicted": "conflicted",
    "error": "problem",
    "ignored": "ignored",
    "loading": "loading",
    "modified": "modified",
    "ok": "clean",
    "stale": "stale",
    "unversioned": "unversioned",
}


@dataclass(frozen=True)
class MenuActionSpec:
    name: str
    label: str
    command: tuple[str, ...] = ()
    tip: str = ""
    icon: str | None = MENU_ICON
    separator: bool = False
    sensitive: bool = True
    children: tuple["MenuActionSpec", ...] = ()


@dataclass(frozen=True)
class MenuGroupSpec:
    name: str
    label: str
    items: tuple[MenuActionSpec, ...]
    tip: str = ""
    icon: str = MENU_ICON


@dataclass(frozen=True)
class LocationWidgetSpec:
    backend: str
    backend_label: str
    head: str
    status: str
    status_label: str
    root: str
    root_label: str
    icon: str
    remote: str = ""
    error: str = ""
    worktree_id: str = ""


@dataclass
class LocationWidgetHandle:
    path: str
    worktree_id: str
    outer: object
    source: object
    details: object
    refresh_attempts: int = 0


class NemoVCSInfoProviderCore:
    def __init__(
        self,
        *,
        cache: status_client.StatusClientCache | None = None,
        seen=None,
        get_status=None,
        query_status=None,
        diagnostics=None,
        max_visible_items: int = DEFAULT_MAX_VISIBLE_ITEMS,
    ):
        if max_visible_items < 1:
            raise ValueError("max_visible_items must be at least 1")
        self.cache = cache if cache is not None else status_client.StatusClientCache()
        self.seen = seen
        self.get_status = get_status
        self.query_status = query_status
        self.diagnostics = (
            diagnostics
            if diagnostics is not None
            else PluginDiagnostics.from_environment()
        )
        self.max_visible_items = max_visible_items
        self.visible_items: OrderedDict[str, object] = OrderedDict()
        self.last_error = ""

    def item_path(self, item) -> str | None:
        try:
            if item.get_uri_scheme() != "file":
                self.log("ignore-item", reason="non-file-uri")
                return None
            location = item.get_location()
            path = location.get_path()
        except Exception as exc:
            self.last_error = str(exc)
            self.log("item-error", error=self.last_error)
            return None

        return str(Path(path).resolve(strict=False)) if path else None

    def update_item(self, item) -> dict[str, str] | None:
        path = self.item_path(item)
        if path is None:
            return None
        self.track_visible_item(path, item)
        record = self.update_path(path)
        emblem = self.apply_emblem(item, record)
        self.log(
            "update-item",
            path=path,
            status=record.get("status", "") if record else "",
            emblem=emblem or "",
        )
        return record

    def update_path(
        self,
        path: str | Path,
        *,
        use_cache: bool = True,
    ) -> dict[str, str] | None:
        cached = self.cache.get(path) if use_cache else None
        if cached is not None:
            self.log(
                "status-cache-hit",
                path=str(path),
                status=cached.get("status", ""),
                worktree_id=cached.get("worktree_id", ""),
            )
            return cached

        records: list[dict[str, str]] = []
        for attempt in range(1, 3):
            try:
                path_strings = [str(path)]
                records = validate_status_records(
                    path_strings,
                    self.query_status_records(path_strings),
                )
                self.cache.update(records)
                break
            except Exception as exc:
                self.last_error = str(exc)
                self.log(
                    "status-error",
                    path=str(path),
                    attempt=attempt,
                    error=self.last_error,
                )
                if attempt == 2:
                    record = local_problem_record(path, self.last_error)
                    if record is not None:
                        self.cache.update([record])
                    return record

        self.last_error = ""
        record = records[0] if records else None
        self.log(
            "status",
            path=str(path),
            status=record.get("status", "") if record else "",
            worktree_id=record.get("worktree_id", "") if record else "",
        )
        return record

    def query_status_records(self, paths: Sequence[str]) -> Sequence[dict[str, str]]:
        if self.query_status is not None:
            return self.query_status(paths)

        if self.seen is not None or self.get_status is not None:
            seen = self.seen or default_seen
            get_status = self.get_status or default_get_status
            seen(paths)
            return get_status(paths)

        return default_query_status(paths)

    def apply_emblem(self, item, record: dict[str, str] | None) -> str | None:
        if not record:
            return None
        if record.get("status", "") == "error" and not record_is_problem(record):
            return None

        emblem = primary_emblem(record.get("status", ""))
        if emblem is None:
            return None

        try:
            item.add_emblem(emblem)
        except Exception as exc:
            self.last_error = str(exc)
            self.log("emblem-error", emblem=emblem, error=self.last_error)
            return None

        return emblem

    def track_visible_item(self, path: str | Path, item) -> None:
        key = status_client.normalize_path(path)
        if key in self.visible_items:
            del self.visible_items[key]
        self.visible_items[key] = item
        self.visible_items.move_to_end(key, last=False)
        while len(self.visible_items) > self.max_visible_items:
            self.visible_items.popitem(last=True)

    def on_status_changed(
        self,
        worktree_id: str,
        changed_paths,
    ) -> list[str]:
        affected_paths = self.affected_visible_paths(worktree_id, changed_paths)
        removed = self.cache.invalidate(worktree_id, changed_paths)
        invalidated = [
            path
            for path in affected_paths
            if self.invalidate_visible_item(path)
        ]
        self.log(
            "status-changed",
            worktree_id=str(worktree_id),
            changed_count=len(changed_paths),
            affected_count=len(affected_paths),
            removed_count=len(removed),
            invalidated_count=len(invalidated),
        )
        return invalidated

    def affected_visible_paths(self, worktree_id: str, changed_paths) -> list[str]:
        changed = [status_client.normalize_path(path) for path in changed_paths]
        affected: list[str] = []
        for path in self.visible_items:
            record = self.cache.get(path)
            # Match by path so an item whose worktree membership just changed
            # (e.g. a directory that became a repository) is refreshed even
            # though its cached record still names the old/empty worktree. Only
            # fall back to the worktree id for pathless whole-worktree signals.
            if changed:
                matched = any(
                    status_client.paths_overlap(path, changed_path)
                    for changed_path in changed
                )
            else:
                matched = (
                    record is not None
                    and record.get("worktree_id") == str(worktree_id)
                )
            if matched:
                affected.append(path)
        return affected

    def invalidate_visible_item(self, path: str | Path) -> bool:
        item = self.visible_items.get(status_client.normalize_path(path))
        if item is None:
            return False

        invalidate = getattr(item, "invalidate_extension_info", None)
        if invalidate is None:
            return False

        try:
            invalidate()
        except Exception as exc:
            self.last_error = str(exc)
            self.log("invalidate-error", path=str(path), error=self.last_error)
            return False
        return True

    def log(self, event: str, **fields) -> None:
        if self.diagnostics is not None:
            self.diagnostics.log(event, **fields)

    def menu_paths(self, items) -> list[str]:
        paths: list[str] = []
        for item in items:
            path = self.item_path(item)
            if path is not None:
                paths.append(path)
        return paths

    def submenu_groups(self, paths: Sequence[str | Path]) -> list[MenuGroupSpec]:
        normalized = [str(Path(path).resolve(strict=False)) for path in paths]
        if not normalized:
            return []

        if all(is_clone_target(path) for path in normalized):
            return [
                MenuGroupSpec(
                    name="NemoVCS::GitMenu",
                    label="Git NemoVCS",
                    tip="Git actions",
                    icon=GIT_ICON,
                    items=tuple(git_clone_menu_specs(normalized)),
                ),
                MenuGroupSpec(
                    name="NemoVCS::SvnMenu",
                    label="SVN NemoVCS",
                    tip="Subversion actions",
                    icon=SVN_ICON,
                    items=tuple(svn_checkout_menu_specs(normalized)),
                ),
            ]

        groups: list[MenuGroupSpec] = []
        for backend_id in matching_backend_ids(normalized):
            if backend_id == "git":
                extras = forge_menu_specs(normalized)
                groups.append(
                    MenuGroupSpec(
                        name="NemoVCS::GitMenu",
                        label="Git NemoVCS",
                        tip="Git actions",
                        icon=GIT_ICON,
                        items=tuple(git_menu_specs(normalized, extras)),
                    )
                )
            elif backend_id == "svn":
                groups.append(
                    MenuGroupSpec(
                        name="NemoVCS::SvnMenu",
                        label="SVN NemoVCS",
                        tip="Subversion actions",
                        icon=SVN_ICON,
                        items=tuple(svn_menu_specs(normalized)),
                    )
                )
        return groups

    def top_level_specs(self, paths: Sequence[str | Path]) -> list[MenuActionSpec]:
        normalized = [str(Path(path).resolve(strict=False)) for path in paths]
        if not normalized:
            return []

        compare_spec = two_path_compare_spec(normalized)
        if compare_spec is not None:
            return [compare_spec]

        if all(is_clone_target(path) for path in normalized):
            return []

        if matching_backend_ids(normalized) and self.diff_paths_visible(normalized):
            return common_top_level_specs(normalized)
        return []

    def diff_paths_visible(self, paths: Sequence[str]) -> bool:
        if not paths:
            return False
        for path in paths:
            record = self.cache.get(path)
            if record is None:
                record = self.update_path(path)
            if record is None or record.get("status", "") not in DIFFABLE_STATUSES:
                return False
        return True

    def location_widget_spec(
        self,
        path: str | Path,
        *,
        use_cache: bool = True,
    ) -> LocationWidgetSpec | None:
        record = self.update_path(path, use_cache=use_cache)
        if record is None:
            return None

        backend = str(record.get("backend", ""))
        root = str(record.get("root", ""))
        if not backend or not root:
            return None

        head = str(record.get("head", "")) or "unknown"
        status = str(record.get("status", ""))
        return LocationWidgetSpec(
            backend=backend,
            backend_label=BACKEND_LABELS.get(backend, backend.upper()),
            worktree_id=str(record.get("worktree_id", "")),
            head=head,
            status=status,
            status_label=STATUS_LABELS.get(status, status or "unknown"),
            root=root,
            root_label=Path(root).name or root,
            icon=BACKEND_ICONS.get(backend, MENU_ICON),
            remote=str(record.get("remote", "")),
            error=str(record.get("error", "")),
        )


class PluginDiagnostics:
    def __init__(self, path: str | Path):
        self.path = Path(path).expanduser()

    @classmethod
    def from_environment(cls):
        path = os.environ.get("NEMOVCS_PLUGIN_LOG")
        return cls(path) if path else None

    def log(self, event: str, **fields) -> None:
        record = {"time": time.time(), "event": event, **fields}
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps(record, sort_keys=True) + "\n")
        except OSError:
            pass


class NemoVCSInfoProviderMixin:
    def __init__(self):
        self.nemovcs_core = NemoVCSInfoProviderCore()
        self.nemovcs_signal_subscription = None
        self.nemovcs_location_details_expanded = False
        self.nemovcs_location_widgets: list[LocationWidgetHandle] = []
        self.subscribe_status_changed()
        self.nemovcs_core.log("provider-init")

    def update_file_info(self, item):
        from gi.repository import Nemo

        self.nemovcs_core.update_item(item)
        return Nemo.OperationResult.COMPLETE

    def get_file_items(self, _window, items):
        paths = self.nemovcs_core.menu_paths(items)
        return self.nemovcs_menu_items(paths)

    def get_background_items(self, _window, item):
        path = self.nemovcs_core.item_path(item)
        return self.nemovcs_menu_items([path] if path else [])

    def get_widget(self, uri, _window):
        path = path_from_uri(uri)
        if path is None:
            return None

        spec = self.nemovcs_core.location_widget_spec(path)
        if spec is None:
            return None
        return self.nemovcs_location_widget(path, spec)

    def nemovcs_menu_items(self, paths: Sequence[str]) -> list[object]:
        top_level_specs = self.nemovcs_core.top_level_specs(paths)
        submenu_groups = self.nemovcs_core.submenu_groups(paths)
        if not top_level_specs and not submenu_groups:
            return []

        from gi.repository import Nemo

        items = [
            self.nemovcs_menu_item(Nemo, spec)
            for spec in top_level_specs
            if not spec.separator
        ]

        for group in submenu_groups:
            items.append(self.nemovcs_submenu_item(Nemo, group))
        items.append(Nemo.MenuItem.new_separator("NemoVCS::AfterMenu"))
        return items

    def nemovcs_submenu_item(self, Nemo, group: MenuGroupSpec):
        submenu_item = Nemo.MenuItem(
            name=group.name,
            label=group.label,
            tip=group.tip,
            icon=group.icon,
        )
        submenu = Nemo.Menu()
        submenu_item.set_submenu(submenu)
        self.nemovcs_append_menu_specs(Nemo, submenu, group.items)
        return submenu_item

    def nemovcs_append_menu_specs(self, Nemo, menu, specs: Sequence[MenuActionSpec]):
        for spec in specs:
            if spec.separator:
                menu.append_item(Nemo.MenuItem.new_separator(spec.name))
                continue
            menu.append_item(self.nemovcs_menu_item(Nemo, spec))

    def nemovcs_menu_item(self, Nemo, spec: MenuActionSpec):
        item = Nemo.MenuItem(
            name=spec.name,
            label=spec.label,
            tip=spec.tip,
            icon=spec.icon,
        )
        if spec.children:
            submenu = Nemo.Menu()
            item.set_submenu(submenu)
            self.nemovcs_append_menu_specs(Nemo, submenu, spec.children)
        elif spec.command:
            item.connect("activate", self.on_menu_item_activate, spec.command)
        if not spec.sensitive:
            set_sensitive = getattr(item, "set_sensitive", None)
            if set_sensitive is not None:
                set_sensitive(False)
            else:
                item.set_property("sensitive", False)
        return item

    def nemovcs_location_widget(self, path: str, spec: LocationWidgetSpec):
        from gi.repository import Gtk, Pango

        outer = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=4)
        outer.set_border_width(4)
        outer.set_hexpand(True)
        outer.set_tooltip_text(location_widget_tooltip(spec))

        box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        box.set_hexpand(True)
        outer.pack_start(box, False, False, 0)

        image = Gtk.Image.new_from_icon_name(spec.icon, Gtk.IconSize.MENU)
        box.pack_start(image, False, False, 0)

        backend = Gtk.Label()
        backend.set_markup(f"<b>{escape(spec.backend_label)}</b>")
        backend.set_xalign(0)
        box.pack_start(backend, False, False, 0)

        expanded = self.nemovcs_location_details_expanded

        source = Gtk.Label(label=location_widget_summary_label(spec))
        source.set_ellipsize(Pango.EllipsizeMode.END)
        source.set_max_width_chars(80)
        source.set_hexpand(True)
        source.set_xalign(0)
        source.set_selectable(True)
        box.pack_start(source, True, True, 0)

        details = self.nemovcs_location_details_widget(Gtk, spec)
        outer.pack_start(details, False, False, 0)

        toggle = Gtk.ToggleButton()
        toggle.set_relief(Gtk.ReliefStyle.NONE)
        toggle.set_active(expanded)
        toggle.set_tooltip_text(
            "Hide repository details" if expanded else "Show repository details"
        )
        toggle.set_image(
            Gtk.Image.new_from_icon_name(
                "pan-up-symbolic" if expanded else "pan-down-symbolic",
                Gtk.IconSize.MENU,
            )
        )
        toggle.connect(
            "toggled",
            self.on_location_details_toggled,
            details,
        )
        box.pack_start(toggle, False, False, 0)

        separator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
        outer.pack_start(separator, False, False, 0)

        self.track_location_widget(path, spec, outer, source, details)

        outer.show_all()
        if not expanded:
            details.hide()
        return outer

    def track_location_widget(
        self,
        path: str,
        spec: LocationWidgetSpec,
        outer,
        source,
        details,
    ) -> LocationWidgetHandle:
        handle = LocationWidgetHandle(
            path=status_client.normalize_path(path),
            worktree_id=spec.worktree_id,
            outer=outer,
            source=source,
            details=details,
        )
        self.nemovcs_location_widgets.append(handle)
        connect = getattr(outer, "connect", None)
        if connect is not None:
            connect("destroy", self.on_location_widget_destroy, handle)
        if spec.status == "loading":
            self.schedule_location_widget_retry(handle)
        return handle

    def on_location_widget_destroy(self, _widget, handle: LocationWidgetHandle) -> None:
        self.nemovcs_location_widgets = [
            item for item in self.nemovcs_location_widgets if item is not handle
        ]

    def nemovcs_location_details_widget(self, Gtk, spec: LocationWidgetSpec):
        grid = Gtk.Grid(column_spacing=10, row_spacing=2)
        grid.set_margin_start(24)

        populate_location_details_widget(Gtk, grid, spec)
        return grid

    def on_location_details_toggled(
        self,
        button,
        details,
    ) -> None:
        from gi.repository import Gtk

        set_location_details_expanded(
            self,
            button.get_active(),
            button,
            details,
            lambda icon: Gtk.Image.new_from_icon_name(icon, Gtk.IconSize.MENU),
        )

    def on_menu_item_activate(self, _item, command: Sequence[str]) -> None:
        launch_command = menu_launch_command(command)
        try:
            subprocess.Popen(launch_command, env=menu_launch_env(command))
        except OSError as exc:
            self.nemovcs_core.last_error = str(exc)
            self.nemovcs_core.log(
                "menu-spawn-error",
                command=" ".join(launch_command),
                error=str(exc),
            )

    def subscribe_status_changed(self) -> bool:
        try:
            self.nemovcs_signal_subscription = subscribe_daemon_status_changed(
                self.on_daemon_status_changed
            )
        except Exception as exc:
            self.nemovcs_core.last_error = str(exc)
            return False
        return True

    def on_daemon_status_changed(self, worktree_id, changed_paths) -> list[str]:
        changed = [str(path) for path in changed_paths]
        invalidated = self.nemovcs_core.on_status_changed(str(worktree_id), changed)
        self.schedule_location_widget_refresh(str(worktree_id), changed)
        return invalidated

    def schedule_location_widget_refresh(
        self,
        worktree_id: str,
        changed_paths: Sequence[str],
    ) -> None:
        try:
            from gi.repository import GLib
        except Exception:
            self.refresh_location_widgets(worktree_id, changed_paths)
            return

        def refresh():
            self.refresh_location_widgets(worktree_id, changed_paths)
            return False

        GLib.idle_add(refresh)

    def refresh_location_widgets(
        self,
        worktree_id: str,
        changed_paths: Sequence[str],
    ) -> None:
        for handle in list(self.nemovcs_location_widgets):
            if not location_widget_handle_affected(handle, worktree_id, changed_paths):
                continue
            self.refresh_location_widget_handle(handle)

    def schedule_location_widget_retry(self, handle: LocationWidgetHandle) -> None:
        if handle.refresh_attempts >= LOCATION_WIDGET_MAX_REFRESH_RETRIES:
            return
        handle.refresh_attempts += 1
        try:
            from gi.repository import GLib
        except Exception:
            self.refresh_location_widget_retry(handle)
            return

        def refresh():
            self.refresh_location_widget_retry(handle)
            return False

        GLib.timeout_add(LOCATION_WIDGET_REFRESH_RETRY_MS, refresh)

    def refresh_location_widget_retry(self, handle: LocationWidgetHandle) -> None:
        if handle not in self.nemovcs_location_widgets:
            return
        spec = self.refresh_location_widget_handle(handle)
        if spec is not None and spec.status == "loading":
            self.schedule_location_widget_retry(handle)

    def refresh_location_widget_handle(
        self,
        handle: LocationWidgetHandle,
    ) -> LocationWidgetSpec | None:
        spec = self.nemovcs_core.location_widget_spec(handle.path, use_cache=False)
        if spec is None:
            return None
        self.apply_location_widget_spec(handle, spec)
        return spec

    def apply_location_widget_spec(
        self,
        handle: LocationWidgetHandle,
        spec: LocationWidgetSpec,
    ) -> None:
        from gi.repository import Gtk

        handle.worktree_id = spec.worktree_id
        if spec.status != "loading":
            handle.refresh_attempts = 0
        handle.source.set_text(location_widget_summary_label(spec))
        handle.outer.set_tooltip_text(location_widget_tooltip(spec))
        clear_container(handle.details)
        populate_location_details_widget(Gtk, handle.details, spec)
        if self.nemovcs_location_details_expanded:
            handle.details.show_all()
        handle.details.queue_resize()


def default_seen(paths):
    from . import statusd_dbus

    return statusd_dbus.call_seen(paths)


def default_query_status(paths):
    from . import statusd_dbus

    return statusd_dbus.call_query_status(paths)


def path_from_uri(uri: str) -> str | None:
    parsed = urlparse(uri)
    if parsed.scheme and parsed.scheme != "file":
        return None
    path = unquote(parsed.path if parsed.scheme else uri)
    return str(Path(path).resolve(strict=False)) if path else None


def compact_text(text: str, *, max_chars: int = LOCATION_BAR_MAX_CHARS) -> str:
    if len(text) <= max_chars:
        return text
    if max_chars <= 1:
        return text[:max_chars]
    return text[: max_chars - 1] + "..."


def location_widget_details(spec: LocationWidgetSpec) -> list[tuple[str, str]]:
    details: list[tuple[str, str]] = [
        ("Worktree", spec.root),
        ("Status", spec.status_label),
    ]
    if spec.head:
        details.append((location_widget_identity_label(spec), spec.head))
    if spec.status == "error" and spec.error:
        details.append(("Problem", spec.error))
    return details


def populate_location_details_widget(Gtk, grid, spec: LocationWidgetSpec) -> None:
    from gi.repository import Pango

    for row, (label_text, value_text) in enumerate(location_widget_details(spec)):
        label = Gtk.Label()
        label.set_markup(f"<b>{escape(label_text)}</b>")
        label.set_xalign(0)
        grid.attach(label, 0, row, 1, 1)

        value = Gtk.Label(label=value_text)
        configure_location_detail_value_label(
            value,
            value_text,
            Pango.EllipsizeMode.END,
        )
        grid.attach(value, 1, row, 1, 1)


def configure_location_detail_value_label(label, text: str, ellipsize_mode) -> None:
    label.set_xalign(0)
    label.set_hexpand(True)
    label.set_ellipsize(ellipsize_mode)
    label.set_max_width_chars(80)
    label.set_selectable(True)
    label.set_tooltip_text(text)


def clear_container(container) -> None:
    get_children = getattr(container, "get_children", None)
    remove = getattr(container, "remove", None)
    if get_children is None or remove is None:
        return
    for child in list(get_children()):
        remove(child)


def location_widget_tooltip(spec: LocationWidgetSpec) -> str:
    return "\n".join(
        f"{label}: {value}" for label, value in location_widget_details(spec)
    )


def location_widget_summary_label(spec: LocationWidgetSpec) -> str:
    source = location_widget_source(spec)
    if spec.backend == "git" and spec.head and spec.head != "unknown":
        return f"{source} ({spec.head})"
    return source


def location_widget_source(spec: LocationWidgetSpec) -> str:
    if spec.status == "loading" and not spec.remote:
        return "loading source..."
    return spec.remote or spec.root


def location_widget_identity_label(spec: LocationWidgetSpec) -> str:
    if spec.backend == "git" and spec.head not in {"unknown", ""}:
        if not spec.head.startswith("detached at "):
            return "Branch"
    return "Head"


def location_widget_handle_affected(
    handle: LocationWidgetHandle,
    worktree_id: str,
    changed_paths: Sequence[str],
) -> bool:
    if handle.worktree_id != str(worktree_id):
        return False
    return not changed_paths or any(
        status_client.paths_overlap(handle.path, changed_path)
        for changed_path in changed_paths
    )


def set_location_details_expanded(
    provider,
    expanded: bool,
    button,
    details,
    image_factory,
) -> None:
    provider.nemovcs_location_details_expanded = expanded
    if expanded:
        details.show_all()
    else:
        details.hide()
    details.get_parent().queue_resize()
    button.set_tooltip_text(
        "Hide repository details" if expanded else "Show repository details"
    )
    icon = "pan-up-symbolic" if expanded else "pan-down-symbolic"
    button.set_image(image_factory(icon))


def default_get_status(paths):
    from . import statusd_dbus

    return statusd_dbus.call_get_status(paths)


def subscribe_daemon_status_changed(callback):
    import dbus.mainloop.glib

    from . import statusd_dbus

    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    return statusd_dbus.subscribe_status_changed(callback)


def menu_launch_command(command: Sequence[str]) -> list[str]:
    if command and command[0] == "nemovcs":
        return [sys.executable, "-m", *command]
    return list(command)


def menu_launch_env(command: Sequence[str]) -> dict[str, str] | None:
    if not command or command[0] != "nemovcs":
        return None

    source_root = str(Path(__file__).resolve().parents[1])
    env = os.environ.copy()
    current = env.get("PYTHONPATH")
    env["PYTHONPATH"] = source_root if not current else f"{source_root}:{current}"
    return env


def primary_emblem(status: str) -> str | None:
    return PRIMARY_EMBLEMS.get(status)


def record_is_problem(record: dict[str, str]) -> bool:
    return bool(record.get("backend") or record.get("root") or record.get("worktree_id"))


def validate_status_records(
    paths: Sequence[str | Path],
    records,
) -> list[dict[str, str]]:
    path_count = len(list(paths))
    validated = [validate_status_record(record) for record in records]
    if len(validated) != path_count:
        raise ValueError("status daemon returned an unexpected record count")
    return validated


def validate_status_record(record) -> dict[str, str]:
    try:
        result = {str(key): str(value) for key, value in dict(record).items()}
    except (TypeError, ValueError) as exc:
        raise ValueError("status daemon returned a malformed record") from exc

    if not result.get("path"):
        raise ValueError("status daemon record is missing path")

    status = result.get("status", "")
    if status not in STATUS_LABELS:
        raise ValueError(f"status daemon returned unknown status: {status}")

    backend = result.get("backend", "")
    if backend and backend not in BACKEND_LABELS:
        raise ValueError(f"status daemon returned unknown backend: {backend}")

    return result


def local_problem_record(path: str | Path, error: str) -> dict[str, str] | None:
    marker = local_vcs_marker(path)
    if marker is None:
        return None

    backend, root, vcs_dir = marker
    return {
        "path": str(Path(path).resolve(strict=False)),
        "backend": backend,
        "worktree_id": f"{backend}:{root}",
        "root": str(root),
        "gitdir": str(vcs_dir),
        "common_gitdir": str(vcs_dir),
        "head": "unknown",
        "remote": "",
        "status": "error",
        "error": error,
    }


def local_vcs_marker(path: str | Path) -> tuple[str, Path, Path] | None:
    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    candidate = candidate.resolve(strict=False)
    current = candidate if candidate.is_dir() else candidate.parent

    while True:
        git_marker = current / ".git"
        if is_git_marker(git_marker):
            return ("git", current, git_marker)

        svn_marker = current / ".svn"
        if is_svn_marker(svn_marker):
            return ("svn", current, svn_marker)

        if current.parent == current:
            return None
        current = current.parent


def is_git_marker(path: Path) -> bool:
    if path.is_dir():
        return (path / "HEAD").exists() or (path / "commondir").exists()
    if not path.is_file():
        return False
    try:
        return path.read_text(encoding="utf-8", errors="replace").startswith("gitdir:")
    except OSError:
        return False


def is_svn_marker(path: Path) -> bool:
    return path.is_dir() and (path / "wc.db").exists()


def matching_backend_ids(paths: Sequence[str | Path]) -> list[str]:
    from . import backends

    ids: list[str] = []
    for backend in backends.registered_backends():
        if all(backend.is_worktree(path) for path in paths):
            ids.append(backend.id)
    return ids


def is_clone_target(path: str | Path) -> bool:
    from . import backends

    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    candidate = candidate.resolve(strict=False)
    return candidate.is_dir() and backends.detect_backend(candidate) is None


def forge_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    """Return the forge-related menu items for a Git repository.

    Two mutually exclusive cases:
      - the repository has a remote that a forge recognizes -> a submenu
        labelled and iconed by the forge, filled with the actions the adapter
        advertises for the current (network-free) context;
      - the repository has no remote -> a "Publish to <forge>..." action for
        each available forge, since publish is how a local repo adopts a forge.
    Anything else (not a repo, no forge, no advertised actions) -> no items.
    """
    from . import forge as forge_registry
    from . import git
    from .forge.base import ForgeContext

    if not paths:
        return []
    root = git.repo_root(paths[0])
    if root is None:
        return []
    remote = git.remote_url(root) or ""

    if remote:
        hosting = forge_registry.detect_forge(remote)
        if hosting is None or not hosting.is_available():
            return []
        context = ForgeContext(
            root=str(root),
            remote_url=remote,
            branch=git.current_branch_name(root),
            worktree_dirty=git.worktree_dirty(root),
            selection=tuple(str(path) for path in paths),
        )
        children = tuple(
            forge_action_spec(item, paths) for item in hosting.actions(context)
        )
        if not children:
            return []
        return [
            MenuActionSpec(
                name="NemoVCS::Forge",
                label=hosting.label,
                tip=f"{hosting.label} actions",
                icon=hosting.icon,
                children=children,
            )
        ]

    return [
        action(
            f"Publish{forge.id}",
            f"Publish to {forge.label}...",
            ["publish-dialog", "--forge", forge.id, *paths],
            icon=forge.icon,
        )
        for forge in forge_registry.registered_forges()
        if forge.is_available()
    ]


def forge_action_spec(item, paths: Sequence[str]) -> MenuActionSpec:
    return MenuActionSpec(
        name=f"NemoVCS::Forge::{item.id}",
        label=item.label,
        command=("nemovcs", "forge", item.id, *paths),
        tip=item.disabled_reason or item.label.removesuffix("..."),
        icon=item.icon or MENU_ICON,
        sensitive=item.enabled,
    )


def git_menu_specs(
    paths: Sequence[str],
    extra_specs: Sequence[MenuActionSpec] = (),
) -> list[MenuActionSpec]:
    specs = [
        action("GitCommit", "Commit...", ["commit-dialog", *paths], icon=COMMIT_ICON),
        action("GitUpdate", "Update...", ["update-dialog", *paths], icon=UPDATE_ICON),
        separator("GitSep0"),
        action(
            "GitStage",
            "Stage...",
            ["stage-dialog", "--operation", "stage", *paths],
            icon=ADD_ICON,
        ),
    ]
    if len(paths) == 1:
        specs.append(
            action("GitRename", "Rename...", ["rename-dialog", *paths], icon=RENAME_ICON)
        )
        switch_spec = git_switch_branch_menu_spec(paths[0])
        if switch_spec is not None:
            specs.append(switch_spec)
    specs.extend(
        [
            action(
                "GitRevert",
                "Revert...",
                ["revert-dialog", *paths],
                icon=REVERT_ICON,
            ),
            action("GitPush", "Push...", ["push-dialog", *paths], icon=PUSH_ICON),
            separator("GitSep1"),
            action("GitStatus", "Status...", ["status-dialog", *paths], icon=STATUS_ICON),
            action("GitLog", "Log...", ["log-dialog", *paths], icon=LOG_ICON),
        ]
    )
    if extra_specs:
        specs.append(separator("GitForgeSep"))
        specs.extend(extra_specs)
    specs.extend(
        [
            separator("GitSep2"),
            action("GitSettings", "Settings...", ["settings-dialog"], icon=SETTINGS_ICON),
            action("GitAbout", "About...", ["about-dialog"], icon=ABOUT_ICON),
        ]
    )
    return specs


def git_switch_branch_menu_spec(path: str) -> MenuActionSpec | None:
    from . import git

    root = git.repo_root(path)
    if root is None:
        return None

    current = git.current_branch_name(root)
    dirty = git.worktree_dirty(root)
    branches = git.recent_branches(root)
    if current and current not in branches:
        branches.insert(0, current)
    branch_locations = git.worktree_branch_locations(root)

    children: list[MenuActionSpec] = []
    for branch in branches:
        if branch == current:
            children.append(
                MenuActionSpec(
                    name=f"NemoVCS::GitSwitchCurrent::{menu_name_fragment(branch)}",
                    label=branch,
                    tip="Current branch",
                    icon="object-select-symbolic",
                    sensitive=False,
                )
            )
            continue
        branch_location = branch_locations.get(branch)
        checked_out_elsewhere = (
            branch_location is not None
            and branch_location.resolve(strict=False) != root.resolve(strict=False)
        )
        branch_tip = branch
        if dirty:
            branch_tip = "Working tree has changes"
        elif checked_out_elsewhere:
            branch_tip = f"Checked out at {branch_location}"
        children.append(
            MenuActionSpec(
                name=f"NemoVCS::GitSwitchBranch::{menu_name_fragment(branch)}",
                label=branch,
                command=("nemovcs", "switch-branch-dialog", str(root), branch),
                tip=branch_tip,
                icon=None,
                sensitive=not dirty and not checked_out_elsewhere,
            )
        )

    if children:
        children.append(separator("GitSwitchBranchSep"))
    children.append(
        MenuActionSpec(
            name="NemoVCS::GitSwitchBranchOthers",
            label="Others...",
            command=("nemovcs", "switch-branch-dialog", str(root)),
            tip="Working tree has changes" if dirty else "Show all branches",
            icon=None,
            sensitive=not dirty,
        )
    )

    return MenuActionSpec(
        name="NemoVCS::GitSwitchBranch",
        label="Switch Branch",
        tip="Working tree has changes" if dirty else "Switch Git branch",
        icon=MODIFIED_MENU_ICON if dirty else GIT_ICON,
        children=tuple(children),
    )


def common_top_level_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    return [
        action("Diff", "Diff...", ["diff-dialog", *paths], icon=DIFF_ICON),
    ]


def two_path_compare_spec(paths: Sequence[str]) -> MenuActionSpec | None:
    if len(paths) != 2:
        return None

    left, right = (Path(path) for path in paths)
    if (left.is_file() and right.is_file()) or (left.is_dir() and right.is_dir()):
        return MenuActionSpec(
            name="NemoVCS::Compare",
            label="Diff...",
            command=("meld", str(left), str(right)),
            tip="Compare selected paths",
            icon=DIFF_ICON,
        )
    return None


def svn_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    specs = [
        action("SvnCommit", "Commit...", ["commit-dialog", *paths], icon=COMMIT_ICON),
        action("SvnUpdate", "Update...", ["update-dialog", *paths], icon=UPDATE_ICON),
        separator("SvnSep0"),
        action(
            "SvnAdd",
            "Add...",
            ["stage-dialog", "--operation", "add", *paths],
            icon=ADD_ICON,
        ),
    ]
    if len(paths) == 1:
        specs.append(
            action("SvnRename", "Rename...", ["rename-dialog", *paths], icon=RENAME_ICON)
        )
    specs.extend(
        [
            action(
                "SvnRevert",
                "Revert...",
                ["revert-dialog", *paths],
                icon=REVERT_ICON,
            ),
            separator("SvnSep1"),
            action("SvnStatus", "Status...", ["status-dialog", *paths], icon=STATUS_ICON),
            action("SvnLog", "Log...", ["log-dialog", *paths], icon=LOG_ICON),
            separator("SvnSep2"),
            action("SvnSettings", "Settings...", ["settings-dialog"], icon=SETTINGS_ICON),
            action("SvnAbout", "About...", ["about-dialog"], icon=ABOUT_ICON),
        ]
    )
    return specs


def git_clone_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    return [
        action(
            "GitInit",
            "Create Repository...",
            ["init-dialog", *paths],
            icon=ADD_ICON,
        ),
        action(
            "GitClone",
            "Git Clone...",
            ["clone-dialog", "--vcs", "git", *paths],
            icon=CHECKOUT_ICON,
        ),
        separator("GitCloneSep1"),
        action(
            "GitCloneSettings",
            "Settings...",
            ["settings-dialog"],
            icon=SETTINGS_ICON,
        ),
        action("GitCloneAbout", "About...", ["about-dialog"], icon=ABOUT_ICON),
    ]


def svn_checkout_menu_specs(paths: Sequence[str]) -> list[MenuActionSpec]:
    return [
        action(
            "SvnCheckout",
            "SVN Checkout...",
            ["clone-dialog", "--vcs", "svn", *paths],
            icon=CHECKOUT_ICON,
        ),
        separator("SvnCheckoutSep1"),
        action(
            "SvnCheckoutSettings",
            "Settings...",
            ["settings-dialog"],
            icon=SETTINGS_ICON,
        ),
        action("SvnCheckoutAbout", "About...", ["about-dialog"], icon=ABOUT_ICON),
    ]


def action(
    name: str,
    label: str,
    args: Sequence[str],
    *,
    icon: str = MENU_ICON,
) -> MenuActionSpec:
    return MenuActionSpec(
        name=f"NemoVCS::{name}",
        label=label,
        command=("nemovcs", *args),
        tip=label.removesuffix("..."),
        icon=icon,
    )


def separator(name: str) -> MenuActionSpec:
    return MenuActionSpec(name=f"NemoVCS::{name}", label="", separator=True)


def menu_name_fragment(text: str) -> str:
    return "".join(char if char.isalnum() else "_" for char in text)
