"""Minimal Nemo extension core for status lookups.

The real nemo-python entry point is generated by the installer so development
installs can point Nemo at this source tree without requiring pip install -e.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

from . import status_client


DEFAULT_MAX_VISIBLE_ITEMS = 2048

PRIMARY_EMBLEMS = {
    "conflicted": "rabbitvcs-conflicted",
    "modified": "rabbitvcs-modified",
    "ok": "rabbitvcs-normal",
}


class NemoVCSInfoProviderCore:
    def __init__(
        self,
        *,
        cache: status_client.StatusClientCache | None = None,
        seen=None,
        get_status=None,
        max_visible_items: int = DEFAULT_MAX_VISIBLE_ITEMS,
    ):
        if max_visible_items < 1:
            raise ValueError("max_visible_items must be at least 1")
        self.cache = cache if cache is not None else status_client.StatusClientCache()
        self.seen = seen
        self.get_status = get_status
        self.max_visible_items = max_visible_items
        self.visible_items: OrderedDict[str, object] = OrderedDict()
        self.last_error = ""

    def item_path(self, item) -> str | None:
        try:
            if item.get_uri_scheme() != "file":
                return None
            location = item.get_location()
            path = location.get_path()
        except Exception as exc:
            self.last_error = str(exc)
            return None

        return str(Path(path).resolve(strict=False)) if path else None

    def update_item(self, item) -> dict[str, str] | None:
        path = self.item_path(item)
        if path is None:
            return None
        self.track_visible_item(path, item)
        record = self.update_path(path)
        self.apply_emblem(item, record)
        return record

    def update_path(self, path: str | Path) -> dict[str, str] | None:
        try:
            seen = self.seen or default_seen
            get_status = self.get_status or default_get_status
            records = self.cache.refresh([path], seen, get_status)
        except Exception as exc:
            self.last_error = str(exc)
            return None

        self.last_error = ""
        return records[0] if records else None

    def apply_emblem(self, item, record: dict[str, str] | None) -> str | None:
        if not record:
            return None

        emblem = primary_emblem(record.get("status", ""))
        if emblem is None:
            return None

        try:
            item.add_emblem(emblem)
        except Exception as exc:
            self.last_error = str(exc)
            return None

        return emblem

    def track_visible_item(self, path: str | Path, item) -> None:
        key = status_client.normalize_path(path)
        if key in self.visible_items:
            del self.visible_items[key]
        self.visible_items[key] = item
        self.visible_items.move_to_end(key, last=False)
        while len(self.visible_items) > self.max_visible_items:
            self.visible_items.popitem(last=True)

    def on_status_changed(
        self,
        worktree_id: str,
        changed_paths,
    ) -> list[str]:
        affected_paths = self.affected_visible_paths(worktree_id, changed_paths)
        self.cache.invalidate(worktree_id, changed_paths)
        return [
            path
            for path in affected_paths
            if self.invalidate_visible_item(path)
        ]

    def affected_visible_paths(self, worktree_id: str, changed_paths) -> list[str]:
        changed = [status_client.normalize_path(path) for path in changed_paths]
        affected: list[str] = []
        for path in self.visible_items:
            record = self.cache.get(path)
            if record is None or record.get("worktree_id") != str(worktree_id):
                continue
            if not changed or any(
                status_client.paths_overlap(path, changed_path)
                for changed_path in changed
            ):
                affected.append(path)
        return affected

    def invalidate_visible_item(self, path: str | Path) -> bool:
        item = self.visible_items.get(status_client.normalize_path(path))
        if item is None:
            return False

        invalidate = getattr(item, "invalidate_extension_info", None)
        if invalidate is None:
            return False

        try:
            invalidate()
        except Exception as exc:
            self.last_error = str(exc)
            return False
        return True


class NemoVCSInfoProviderMixin:
    def __init__(self):
        self.nemovcs_core = NemoVCSInfoProviderCore()
        self.nemovcs_signal_subscription = None
        self.subscribe_status_changed()

    def update_file_info(self, item):
        from gi.repository import Nemo

        self.nemovcs_core.update_item(item)
        return Nemo.OperationResult.COMPLETE

    def subscribe_status_changed(self) -> bool:
        try:
            self.nemovcs_signal_subscription = subscribe_daemon_status_changed(
                self.nemovcs_core.on_status_changed
            )
        except Exception as exc:
            self.nemovcs_core.last_error = str(exc)
            return False
        return True


def default_seen(paths):
    from . import statusd_dbus

    return statusd_dbus.call_seen(paths)


def default_get_status(paths):
    from . import statusd_dbus

    return statusd_dbus.call_get_status(paths)


def subscribe_daemon_status_changed(callback):
    import dbus.mainloop.glib

    from . import statusd_dbus

    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    return statusd_dbus.subscribe_status_changed(callback)


def primary_emblem(status: str) -> str | None:
    return PRIMARY_EMBLEMS.get(status)
